#!/usr/bin/python
# -*- python -*-

import MySQLdb
# docs at http://mysql-python.sourceforge.net/MySQLdb.html

import string
import common
import noun
import sys
import codecs
import dsn
import argparse

def lookup(word):
    word = word.lower()
    word = db.escape_string(word)
    word = unicode(word, 'utf8')

    q = """
select
    pos_name,
    word,
	concat(attrkey, ':') attrkey,
    attrvalue,
    pf.sort_order
from
    mashup
inner join pos_form pf on pf.attribute_id = mashup.attribute_id and pf.pos_id = mashup.pos_id
where
	word = '%s'
""" % (word)

    c.execute(q)

    result = {}
    pos=''
    for row in c.fetchall():
        d = dict(zip(['name', 'word', 'attrkey', 'value', 'sort_order'],
                 row))
        result[d['attrkey']] = d['value']
        pos = d['name']

    if len(result) == 0:
        print "%s NOT FOUND:  %s" % ('#' * 33, word)
        return

    # get the max width of all attr keys
    max_width = 0
    for r in result.keys():
        if len(r) > max_width:
            max_width = len(r)

    print "%s %s: %s" % ('=' * 33, word, pos)
    for k in result.keys():
        print "%s %s" % (string.ljust(k, max_width),
                         result[k])

parser = argparse.ArgumentParser()
parser.add_argument("word",
                    nargs='+',
                    help="word to look up")
args = parser.parse_args()

# https://pythonhosted.org/kitchen/unicode-frustrations.html
utf8writer = codecs.getwriter('utf8')
sys.stdout = utf8writer(sys.stdout)

db = dsn.getConnection()
c = db.cursor()

for word in args.word:
    lookup(word)

