#!/usr/bin/env python

from dlernen import quiz_sql
from dlernen import dsn

q = quiz_sql.build_quiz_query('genders')
db = dsn.getConnection()
c = db.cursor(dictionary=True)

done = False
while not done:
    c.execute(q)
    for row in c.fetchall():
        prompt = "answer, q to quit --[%s]--> " % row['word']
        prompt = prompt.encode('utf-8')
        answer = input(prompt).strip().lower()
        while len(answer) == 0:
            answer = input(prompt).strip().lower()
    
        if answer == row['value']:
            print('ja')
            row['correct_count'] += 1
        elif answer == 'q':
            done = True
            continue
        else:
            print('nein:  %s %s' % (row['value'], row['word']))
    
        row['presentation_count'] += 1
    
        u = """
    insert into quiz_score
    (quiz_id,word_id,attribute_id,presentation_count,correct_count)
    VALUES
    (%(quiz_id)s, %(word_id)s, %(attribute_id)s, %(presentation_count)s, %(correct_count)s)
    on duplicate key update
    presentation_count = values(presentation_count),
    correct_count = values(correct_count)
    """
    
        c.execute(u, row)
        db.commit()
        
c.close()
db.close()

print('auf wiedersehen')
