#!/usr/bin/env python

from dlernen import config
import argparse
import requests
from pprint import pprint
import sys


def get_next_word_to_test(wordlist_ids):
    url = "%s/api/quiz_data/%s" % (config.Config.DB_URL, quiz_key)
    if wordlist_ids:
        wordlist_ids = ','.join(list(map(str, wordlist_ids)))
        url = "%s?wordlist_id=%s" % (url, wordlist_ids)
    r = requests.get(url)
    quiz_data = r.json()

    if quiz_data:
        return quiz_data[0]


# usage
#
# quiz <quiz_key>
# show available quizzes
# filter by list

if __name__ == '__main__':
    url = "%s/api/quiz" % config.Config.DB_URL
    r = requests.get(url)
    result = r.json()
    available_quizzes = {x['quiz_key'] for x in result}
    l = '\n'.join(sorted(list(available_quizzes)))
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
                                     description="""
available quizzes:

%(available_quizzes)s
""" % {
    'available_quizzes': l
    })

    parser.add_argument("quiz")
    parser.add_argument('-l', '--listids',
                        nargs='+',
                        type=int,
                        help='id of word list to use')

    cl_args = parser.parse_args()

    if cl_args.quiz not in available_quizzes:
        print("no such quiz:  %s" % cl_args.quiz)
        sys.exit()

    quiz_key = cl_args.quiz
    if quiz_key in {'definitions', 'plurals'}:
        print("there is a separate quiz app for %s" % quiz_key)
        sys.exit()

    while True:
        quiz_me = get_next_word_to_test(cl_args.listids)
        if not quiz_me:
            print("es gibt keine Welten mehr zu erobern")
            break

        attrkey = list(quiz_me['attributes'].keys())[0]
        answer = input("%s [%s], q to quit ---> " % (quiz_me['word'], attrkey))

        # answer = str(answer, 'utf8').strip().lower()
        answer = answer.strip()

        while not answer:
            answer = input("%s [%s], q to quit ---> " % (quiz_me['word'], attrkey))
            answer = answer.strip()

        if answer == 'q':
            break

        payload = {
            "quiz_id": quiz_me['quiz_id'],
            "word_id": quiz_me['word_id'],
            "attribute_id": quiz_me['attributes'][attrkey]['attribute_id'],
            "presentation_count": quiz_me['attributes'][attrkey]['presentation_count'],
            "correct_count": quiz_me['attributes'][attrkey]['correct_count']
        }

        if answer == quiz_me['attributes'][attrkey]['attrvalue']:
            print("richtig")
            payload['correct_count'] += 1
        else:
            print("falsch:  %s" % quiz_me['attributes'][attrkey]['attrvalue'])

        payload['presentation_count'] += 1

        url = "%s/api/quiz_data" % config.Config.DB_URL
        r = requests.post(url, data=payload)

    print('bis bald')