#!/usr/bin/env python

import argparse
from app_common import *
from pprint import pprint


if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
                                     description="""
quiz_definitions (no args)
all words

quiz_definitions -l <wordlist_id> <wordlist_id> ...
all from a list

quiz_definitions -n <x> -r
n randomly chosen

quiz_definitions -n <x> -l <wordlist_id> <wordlist_id> ...
n randomly chosen from lists

quiz_definitions -n <x>
n most recent

THE -n AND -r OPTIONS NO LONGER WORK
""")

    # TODO - restore word recency feature.

    parser.add_argument('-l', '--listids',
                        nargs='+',
                        type=int,
                        help='id of word list to use')
    parser.add_argument('-n', '--nwords',
                        type=int,
                        default=10,
                        help='quiz the n most recently added words.  defaults to 10.')
    parser.add_argument('-r', '--recent',
                        action='store_true',
                        help='pick most recently added words and quiz them.')
    cl_args = parser.parse_args()

    wordlist_ids = cl_args.listids if cl_args.listids else None

    done = False
    counter = 0
    while not done:
        row = get_next_word_to_test(wordlist_ids, 'definitions')

        if not row:
            print("es gibt keine Welten mehr zu erobern")
            break

        counter += 1
        print("[%s]" % counter, end=' ')

        if 'article' in row:
            print(row['article'], end=' ')

        print(row['word'])
        prompt = "hit return for answer, q to quit:  --> "
        answer = input(prompt).strip().lower()

        if answer.startswith('q'):
            done = True
            break

        print(row['attributes']['definition']['attrvalue'])

        prompt = "correct? --> "
        answer = input(prompt).strip().lower()

        payload = {
            "quiz_id": row['quiz_id'],
            "word_id": row['word_id'],
            "attribute_id": row['attributes']['definition']['attribute_id'],
            "presentation_count": row['attributes']['definition']['presentation_count'],
            "correct_count": row['attributes']['definition']['correct_count']
        }

        while len(answer) == 0:
            answer = input(prompt).strip().lower()

        if answer.startswith('y'):
            payload['correct_count'] += 1

        payload['presentation_count'] += 1

        url = "%s/api/quiz_data" % config.Config.DB_URL
        r = requests.post(url, data=payload)

    print('bis bald')
