#!/bin/bash
# -*- shell-script -*-

if [ $# -lt 1 ]; then
    echo "arg count"
    exit 1
fi

w="$1"

cat <<EOF | mysql -u german -D deutsch -t
select
	p.name,
	w.word,
	a.attrkey,
	wa.value
from
	pos p,
	word w,
	attribute a,
	word_attribute wa,
	words_x_attributes_v v
where
	v.pos_id = p.id	and
	v.attribute_id = a.id	and
	v.word_id = w.id and
	wa.attribute_id = v.attribute_id	and
	wa.word_id = w.id and
	w.word = '$w'
EOF

