#!/bin/bash
# -*- shell-script -*-

nwords=10
regex=""
orderby="rand()"
datecolumn=""

function usage() {
    echo "usage: $1 [-d] [-r <regex>] [-n <nwords>]
 -n <nwords> number of words to select, default 10
 -d          select last nwords added instead of random selection
"
}

while getopts "n:r:d" opt; do
    case $opt in
	d)
	    orderby="t.added desc"
	    datecolumn=", date(t.added) added"
	    ;;
	n)
	    nwords=$OPTARG
	    ;;
	\?)
	    usage $0
	    exit 1
	    ;;
	:)
	    usage $0
	    exit 1
	    ;;
    esac
done

cat <<EOF | mysql -t
select
	lpad(t.name, 9, ' ') name, -- part of speech
	rpad(concat(ifnull(wa.value, '   '), ' ', t.word), 30, ' ') word,
	t.value definition
        $datecolumn
from
(
	select
		p.name, w.word, w.added, wa.*
	from
		word w
	inner join word_attribute wa on w.id = wa.word_id
	inner join attribute a on wa.attribute_id = a.id
	inner join pos p on p.id = w.pos_id
	where
		a.attrkey = 'definition'
) t
left join
word_attribute wa
on t.word_id = wa.word_id and wa.attribute_id = 1

order by $orderby
limit $nwords
EOF

