use deutsch;

\W

create table if not exists trennbar_vorsilbe
(
		vorsilbe varchar(25) not null primary key,
		definition varchar(512)
) engine=innodb;

insert ignore into trennbar_vorsilbe values
('ab', 'away from'),
('an', 'at, begin, on, onward, to, toward'),
('auf', 'on, open, out, up'),
('aus', 'out, outward, missing'),
('auseinander', 'apart from'),
('bei', 'along, with'),
('da', 'there'),
('dabei', 'remaining there'),
('dar', ''),
('daran', ''),
('dazwischen', ''),
('durch', 'through; entering and completing a process'),
('ein', 'in, into, inward'),
('empor', 'upwards'),
('entgegen', 'toward; in opposition to, counter'),
('entlang', 'entlang.  works with most verbs of motion'),
('entzwei', 'in two, in half; asunder'),
('fehl', 'false, going wrong, fail'),
('fern', 'far, tele-'),
('fest', 'firm or fixed'),
('fort', 'forth, onward, continuing'),
('frei', 'free, clear'),
('gegenüber', 'across from, opposite'),
('gleich', 'equal, concurrent'),
('heim', 'home'),
('her', 'hither; motion toward the speaker'),
('herab', ''),
('heran', ''),
('herauf', ''),
('heraus', ''),
('herbei', ''),
('herein', ''),
('herüber', ''),
('herum', ''),
('herunter', ''),
('hervor', ''),
('hin', 'thither; motion away from the speaker'),
('hinab', ''),
('hinauf', ''),
('hinaus', ''),
('hinein', ''),
('hinterher', ''),
('hinunter', ''),
('hinweg', ''),
('hinzu', ''),
('hoch', ''),
('los', ''),
('mit', ''),
('nach', ''),
('nebenher', ''),
('nieder', ''),
('statt', ''),
('um', ''),
('vor', ''),
('voran', ''),
('voraus', ''),
('vorbei', ''),
('vorüber', ''),
('vorweg', ''),
('weg', ''),
('weiter', ''),
('wieder', ''),
('zu', ''),
('zurecht', ''),
('zurück', ''),
('zusammen', '')
;
